Add mixin for the IBM-DB2 integration
observIQ/ibm-db2-prometheus-exporter pull request #4
Opened 2023-06-19 19:01 UTC by dpaasman00

This mixin adds 1 dashboard and 3 alerts

<img width="2560" alt="Screenshot 2023-06-19 at 2 28 49 PM" src="https://github.com/observIQ/ibm-db2-prometheus-exporter/assets/122491662/64b3e96b-8421-43d6-b887-99ae6f19cc5a">
<img width="2559" alt="Screenshot 2023-06-19 at 2 28 58 PM" src="https://github.com/observIQ/ibm-db2-prometheus-exporter/assets/122491662/9fe87e65-9cb5-4b03-a7ea-92bae3fdb987">

2023-06-20 18:16 UTC, schmikei requested changes
Just some small changes. Overall looks good and passes the lint :)

2023-06-20 18:16 UTC, schmikei commented on mixin/.lint
> +    entries:
Is this unfinished?

2023-06-20 18:16 UTC, schmikei commented on mixin/jsonnetfile.json
> +  }
```suggestion
  }
  
```

2023-06-20 18:16 UTC, schmikei commented on mixin/jsonnetfile.lock.json
> +  }
```suggestion
  }
  
```

2023-06-20 18:16 UTC, schmikei commented on mixin/README.md
> +![First screenshot of the overview dashboard](https://storage.googleapis.com/grafanalabs-integration-assets/snowflake/screenshots/ibm_db2_overview_1.png)
I would leave a TODO to get screenshots uploaded since these 404

2023-06-20 18:16 UTC, schmikei commented on mixin/README.md
> +- IBM DB2 overview
```suggestion

- IBM DB2 overview
```

Just adding whitespace :)

2023-06-20 20:38 UTC, kuiperda requested changes

2023-06-20 20:38 UTC, kuiperda commented on mixin/.lint
> +    reason: "Based on new convention we are using variable names prometheus_datasource and loki_datasource where as linter expects 'datasource'"
Would actually add this last (empty) rule back in, as lint fails without it but specific panel entries aren't actually needed. 

run `make lint` to see this

2023-06-20 20:38 UTC, kuiperda commented on mixin/README.md
> +
Usually we've added a few other things to the readme, namely alerts and how to configure disabling Loki logs. go to jsonnet-libs and checkout feat/sap-hana for an example readme.

2023-06-20 20:38 UTC, kuiperda commented on mixin/README.md
> +
pretty much just these sections
```
and the following alerts:

- SapHanaHighCpuUtilization
- SapHanaHighPhysicalMemoryUsage
- SapHanaMemAllocLimitBelowRecommendation
- SapHanaHighMemoryUsage
- SapHanaHighDiskUtilization
- SapHanaHighSqlExecutionTime
- SapHanaHighReplicationShippingTime
- SapHanaReplicationStatusError

Default thresholds can be configured in `config.libsonnet`.

```js
{
  _config+:: {
    alertsCriticalHighCpuUsage: 80, // percent 0-100
    alertsCriticalHighPhysicalMemoryUsage: 80, // percent 0-100
    alertsWarningLowMemAllocLimit: 90, // percent 0-100
    alertsCriticalHighMemoryUsage: 80, // percent 0-100
    alertsCriticalHighDiskUtilization: 80, //percent 0-100
    alertsCriticalHighSqlExecutionTime: 1, // second
    alertsCriticalHighReplicationShippingTime: 1, //second
  },
}
```

```
To get SAP HANA trace logs, [Promtail and Loki needs to be installed](https://grafana.com/docs/loki/latest/installation/) and provisioned for logs with your Grafana instance. The default directory for trace files is `/opt/hana/shared/<sid>/HDB<insnr>/<host>/trace/` e.g. `/opt/hana/shared/ID0/HDB00/hana-0/trace/*.trc`

SAP HANA trace logs are enabled by default in the `config.libsonnet` and can be removed by setting `enableLokiLogs` to `false`. Then run `make` again to regenerate the dashboard:


{
  _config+:: {
    enableLokiLogs: false,
  },
}


## Alerts overview

SapHanaHighCpuUtilization: CPU utilization is high.
SapHanaHighPhysicalMemoryUsage: Current physical memory usage of the host is approaching capacity.
SapHanaMemAllocLimitBelowRecommendation: Memory allocation limit set below recommended limit.
SapHanaHighMemoryUsage: Current SAP HANA memory usage is approaching capacity.
SapHanaHighDiskUtilization: SAP HANA disk is approaching capacity.
SapHanaHighSqlExecutionTime: SAP HANA SQL average execution time is high.
SapHanaHighReplicationShippingTime: SAP HANA system replication log shipping delay is high.
SapHanaReplicationStatusError: SAP HANA system replication status signifies an error.
```

2023-06-20 20:38 UTC, kuiperda commented on mixin/config.libsonnet
> +    alertsHighLockWaitTime: 2000,
update this with the comments for units

2023-06-20 20:38 UTC, kuiperda commented on mixin/jsonnetfile.lock.json
> +        "version": "30280196507e0fe6fa978a3e0eaca3a62844f817",
delete this lock file and the vendor folder, then run `jb install` in mixin, version can be updated

2023-06-21 15:02 UTC, kuiperda approved these changes

2023-07-06 19:59 UTC, closed without merging